### ISSUE TITLE
Question about event and task creation

### ISSUE THREAD

**Issue by ma00** [anufrievroman/calcure#19]
Hi, is this possible to automate the creation of task and event, like adding these with a python command?

**Comment by anufrievroman** [comment]
Hi, not at the moment, but I plan to extend cli features to support it. At the moment, we support [several user arguments](https://github.com/anufrievroman/calcure/wiki/User-arguments) , so I plan to add support for creation of tasks and events so that you could just run something like:
`calcure --task="My new task"`
Then you can use it in any scripting language. Does this sound like what you would like to see?

**Comment by ma00** [comment]
Exactly!

**Comment by anufrievroman** [comment]
Okay. I roughly implemented that for you in d2a34cd0353299282af6a379c76e58435097ab39. It should become available in version 2.1. For example, you can run:
`calcure --event="2022-06-12-My new event"`
`calcure --task="My new task"`
In the future, I plan a wider support of most of the functions of TUI interface via CLI interface but so far so good.

**Comment by anufrievroman** [comment]
I'll close this issue then. If you have some other ideas, feel free to share :)

**Comment by ma00** [comment]
thanks!
