### ISSUE TITLE
Set colors for different calendars

### ISSUE THREAD

**Issue by MrOnak** [anufrievroman/calcure#40]
Just started to try out calcure, now that it supports .ics files.
I don't seem to find an option to configure specific colors for different calendars, i.e. green for my personal calendar, yellow for the shared family calendar.

**Comment by MrOnak** [comment]
Thanks for sharing your thoughts! Here's mine: My usecase is that usually I look at my various personal, work and shared calendars on one mobile device or another. The "default" way to distingquish entries from multiple calendars in one view seems to be color. So having the same color assigned to the same calendar across all devices makes sense to me.

I get what you're saying about priorities though. If priority colors is what your users are used to, I wouldn't change it. But from a UX perspective, I wouldn't mix them up as well. Maybe do one with colors and the other with icons, consequently.

my 2 cents :)

**Comment by anufrievroman** [comment]
### Note to myself
I tried to rewrite by parsing ics calendars into a list of object of class Collection instead of all into one Collection. The problem arises later when the entire program expects an object of class Collection at every View, not a list of them. Rewriting this way will require lots of (rather dirty) fixes everywhere, so I abandoned this approach. 

### Future plan
A better way might be just to add a property to each item indicating from which calendar it was imported, and coloring it accordingly. That could be a much easier fix, but might still require a rewrite in the future.

**Comment by anufrievroman** [comment]
Roughly implemented different colors for different ics calendars in 6cd24c0b4b387efc9e9d43f512bdfbc64943fd81
Please update `pip install --upgrade calcure` and it should work out of the box. In your config, in Colors section, you can set your colors like:
```
color_ics_calendars = 2,4,6,3
```
i.e. list of colors for your ics calendars (not more than 10).

![image](https://user-images.githubusercontent.com/42904990/222138414-a4bbd93c-8863-47f5-a974-75407bf67deb.png)

**Comment by MrOnak** [comment]
Seems to work fine :) thanks!
