### ISSUE TITLE
Sync Calcurse events and tasks

### ISSUE THREAD

**Issue by noisyBrain** [anufrievroman/calcure#48]
Hi! First of all, thanks for this great TUI. I recently found it and it seems very useful!

I was wondering if there is a way to sync events and tasks from Calcurse automatically when run the app.

Thanks in advance!

**Comment by anufrievroman** [comment]
Hi, thank you :)
As you may have seen already, there is a possibility of import from Calcurse on `C`. This is a migration tool if you'd like to switch to Calcure or just try it out.  I.e. it will just take events and tasks from Calcurse database and make then native in Calcure.

However, writing a full sync functionality (i.e. reading and editing) is not planned, for the following reasons:
- This will require writing a large saving module compatible with Calcurse's format, and also additional complexity layers will need to be introduced to operate two databases instead of one.
- I would like to avoid modifying files made by other programs, because if I make a mistake it may ruin the file for that program.
- Calcure and Calcurse are very similar in functionality, so it is hard to imagine that many people would need to use both and keep them synced. The import function should be enough to migrate if you choose Calcure.
- Any sync functionality is planned to be achieved via .ics files (for now only reading is working).
- In principle, I wouldn't mind if someone wrote this functionality, but personally, with very limited time for this project, I must focus on other aspects of the program.

**Comment by noisyBrain** [comment]
Hey, thanks for your response and sorry for reply so late. I didn't see the notification.
I totally agree with you. It's just that I found some features from Calcurse that may improve Calcure, than's why I suggested a full sync :)
