### ISSUE TITLE
What's the best font for calcure?

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#6]
What's the best font for calcure?
![image](https://user-images.githubusercontent.com/23485114/151898181-3f3a1b13-0b94-45b2-8058-cb0580d05665.png)

**Comment by anufrievroman** [comment]
By default, it should work with any font, because it uses the unicode icons included in most default fonts.

In my screenshot, I used [NerdFont](https://www.nerdfonts.com/), just to have a bit nicer icons.

Also in some terminals, there are issues with unicode, then you can switch off unicode icons in the parameters.
However, I am puzzled by your screenshot, because it does show the icon and then shows a missing one after, but I don't think there should be any icon after the holidays icon... I'll check. This is on Windows, right?

**Comment by xmha97** [comment]
Thanks for your explanation
The problem is with the default Windows console.
![image](https://user-images.githubusercontent.com/23485114/151899622-3f528be0-02fa-42b7-8706-2f379b11b873.png)

**Comment by xmha97** [comment]
Calcure on [eDEX-UI](https://github.com/GitSquared/edex-ui)

![Calcure on eDEX-UI](https://user-images.githubusercontent.com/23485114/151923723-0e3c4f69-62dd-4997-bd08-a4a64e661147.png)
