### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#63]
On Ubuntu, colors are displayed correctly.

![image](https://github.com/anufrievroman/calcure/assets/23485114/76a091b0-c13e-4344-a465-dba3d8c8f0de)

But on Windows, colors are not displayed correctly, maybe invert.

![image](https://github.com/anufrievroman/calcure/assets/23485114/03338aa8-2c12-42bf-9a40-1e69d888974a)

**Comment by anufrievroman** [comment]
It's not really inverted, but basically each terminal has its own 7 colors and it looks like Windows terminal is doing something strange and these 7 colors are not set in the same order, because with many other terminals I tested it worked fine.
Maybe you can check settings of the terminal, is there something about colors?
In any case, again, it seems to me that it's something calcure can't change.

**Comment by anufrievroman** [comment]
I'll assume this issue is just just terminal specific and really related to calcure.
