### ISSUE TITLE
Task view disable or update automatically

### ISSUE THREAD

**Issue by kushagraa-j** [anufrievroman/calcure#8]
Thanks for making this calendar! its absolutely meets my needs.

One thing i wanted to address was, i use calcure with taskwarrior so,
i would rather not want task view at all, or if i hav it, i would want it to update automatically with taskwarrior.

Thanks for reading!

**Comment by anufrievroman** [comment]
Hello, I'm happy it is useful for you!

Auto update of tasks from another program is a bit philosophically difficult to solve. See, now it is a simple import from taskwarrior, but imported tasks become native to calcure and live as normal tasks ever after. So, it is a migration tool, not a sync tool. If I make a real sync tool, I'd need to be able to edit/delete tasks from taskwarrior from within calcure, which means messing with a file from another program. Plus, it's a big duplication of effort to support all operations with several file formats.

I can realistically propose to implement three solutions:
1) Autoimport taskwarrior tasks on startup. So new tasks are added, but if you have deleted some tasks from within taskwarrior they won't be deleted in calcure (because they were already imported).
2) View-only experience, where you see taskwarrior's task below native calcure tasks, without ability to edit them.
3) Perhaps to add some missing task features to convince you to switch from taskwarrior :) Maybe some cli commands or something else?

Sorry, I cannot offer better integration with taskwarrior because it would essentially be writing a client for taskwarrior, which might be a good thing but should be a separate program.

**Comment by anufrievroman** [comment]
About disabling task view, I don't know if it is really necessary. I mean, you can just never switch to it, and you'll never see, it's not like you need to somehow explicitly disable it. Sorry if I misunderstand what you mean.
