### ISSUE TITLE
Keybindings hints should respect unicode setting

### ISSUE THREAD

**Issue by jose1711** [anufrievroman/calcure#83]
Even with `use_unicode_icons` set to `No` `calcure` tries to use display left/right arrows: 🠒 🠐. With fonts missing unicode support this may lead to:
![obrázok](https://github.com/anufrievroman/calcure/assets/1406222/68053545-a2f9-44c1-ae2b-ee0ca198e646)

**Comment by anufrievroman** [comment]
Well, since these strings are parts of the translation files it's easier just to delete these symbols from help screen and just keep n and p instead of trying to somehow take that option into account.

In the documentation users can see full list of key bindings, which also includes h,j,k,l and arrow keys.

**Comment by jose1711** [comment]
or perhaps this would be an option:
```
n,<-  Next month (day)
p,->  Previous month (day)
```

**Comment by anufrievroman** [comment]
I'll just mention the arrow keys together with Vim keys at the bottom of the help screen.
Changed in 3117a8c63474c76b3529ae213dd85945e885a938
