### ISSUE TITLE
Automatic reloading

### ISSUE THREAD

**Issue by CyanMonkey** [anufrievroman/calcure#92]
I have a cron job that runs vdirsyncer every 30 minutes to sync with a caldav server. However any new events/changes that are downloaded to my computer are not updated in calcure. I have to quit calcure and then reopen calcure for the new events to propagate. 

I am planning to leave calcure running indefinitely in a tmux session with my MUA, neomutt, and detach and attach the session as needed. 

Does anyone have any suggestions?

**Comment by anufrievroman** [comment]
I think it can be implemented. Would you prefer auto-reload every N minutes or reload upon key press? The little problem is that for some users it takes a long time to load huge ics files so it is not a default behavior.

**Comment by CyanMonkey** [comment]
I think the reload every N minutes would be best for me but I would be happy with any implementation you can come up with. 

Perhaps add in both but give the user the option to toggle the reload after N minutes?

**Comment by anufrievroman** [comment]
The most minimal implementation I could think of I just made in 4b44f3b5345373ccc5d01bf0c9527a344c71af59 Now pressing `Q` will reload ics user data. This will appear in the next version, or you can try by installing from main branch.

```
pipx install git+https://github.com/anufrievroman/calcure
```
About periodic reload I am not sure, I'll see how to better make it, because now we don't really measure past time in the program.

**Comment by anufrievroman** [comment]
Okay, then I'll close the issue, thank you for your suggestion.
