### ISSUE TITLE
Update AUR Package to 3.0.0+

### ISSUE THREAD

**Issue by dvragulin** [anufrievroman/calcure#93]
Dear Roman,
Sorry for the open issue, but we are really looking forward to updating your awesome app in AUR repository.
Unfortunately, version 2.x is being downloaded from pip.
Thanks for understanding and your work! :heart:

**Comment by anufrievroman** [comment]
Hi, thank you!
I thought it was just updated as discussed in #41 
To me, AUR [now has 3.0 version](https://aur.archlinux.org/packages/calcure) in it (just checked). Or am I missing something?

**Comment by dvragulin** [comment]
Yes, it is displayed as version 3.0.1, but if you check the package version, it will be 2.9.6.
A similar situation occurs when installing via PIP.

Why am I asking? I'm really looking forward to the feature that was implemented in issue #68.
Here is the output of my terminal:
```
~ » pacman -Q calcure
calcure 3.0-1
~ » calcure -v
Calcure - version 2.9.6
```

--
regards

**Comment by anufrievroman** [comment]
Ah I see, that's my bad, I just forgot to update that -v output, but rest assured that it's version 3.0 you are running. You can also check it by pressing ? key, it should say 3.0.

**Comment by anufrievroman** [comment]
> Why am I asking? I'm really looking forward to the feature that was implemented in issue #68.

So, if with this version you still don't see your multiday events, please let us know.

**Comment by dvragulin** [comment]
> So, if with this version you still don't see your multiday events, please let us know.

Yes, I still don't see any recurring events

> You can also check it by pressing ?

Yes, version 3.0 is installed
![Screenshot_2023-12-22_203328](https://github.com/anufrievroman/calcure/assets/26843784/d1932169-4503-4888-bc89-512bc603d381)

I have several (Google and MS Outlook) calendars, I connect to each of them by adding the `ics_event_files` setting to config.ini:
```ini
[Parameters]
ics_event_files = https://mail.myorg.com/owa/calendar/token/calendar.ics,https://calendar.google.com/calendar/ical/token/basic.ics,another-one,another-one,etc
```

**Comment by anufrievroman** [comment]
Just to make sure, there are two different types of recurring events: 1) multiday events (i.e. it starts and continues over several days), which are supported, and 2) recurring events (which are repeated with some periodicity on other days/weeks/months), which are not supported yet. If your evens are of the second type, it's a work in progress. Previously it couldn't be supported because of the limits of the library, but now we switched to `icalendar` so maybe it's possible. I think different calendars may code recurrence differently, so if you have some minimal example of such file, that would be helpful. I'll open a separate issue for this problem.

**Comment by dvragulin** [comment]
Yes, I meant exactly recurring events. I think this aspect is actually very important, because part of our life consists of a schedule - periodic events that repeat from day to day. Thank you so much for your understanding and assistance, I really look forward to the implementation of this feature.
