### ISSUE TITLE
Broken daily view

### ISSUE THREAD

**Issue by dvragulin** [anufrievroman/calcure#96]
Dear Roman, I'm sorry, but it's me again.
I noticed incorrect calendar behavior in the Daily View:
1. No more than 2 events are added to the list for one day (screen 1 and 2).
2. If the third event has a long name, then it is layered on the next day (screen 1).
3. If there are more than two events on the first day and there are no events on the next day, then the third and subsequent events are postponed to the next day (screen 2)

Screen 1:
![Screenshot_2023-12-23_154235](https://github.com/anufrievroman/calcure/assets/26843784/a6db2801-ef2c-4c83-9490-1ff8909f872a)

Screen 2:
![Screenshot_2023-12-23_155838](https://github.com/anufrievroman/calcure/assets/26843784/72de0a9c-e9fe-488c-88ee-cc126b30f9cf)

**Comment by anufrievroman** [comment]
Hmm, that's very strange. To me, it displays correctly:
![image](https://github.com/anufrievroman/calcure/assets/42904990/14e04467-78dd-4c5f-b441-0a827b95e354)
Thank you for reporting, I'll think what may cause that. But for example, if you use native events (not from ics calendars) and add many of them into one day, does that display correctly?

**Comment by anufrievroman** [comment]
### NOTE TO MYSELF:
The only reason I can imagine this occurring is that the property `self.num_events_this_day` of `class DailyView(View)` remains equal to zero and not equal to the actual number of rendered events. That's why all events of the day are displayed, and then next days is simply displayed on top of those events (after default 2 lines spacing) as if the events were not there. This seems to be specific to these particular events because I could not reproduce it no matter what. 
### Possible ways to approach it
- Could it have something to do with their time or timezone (unlikely)? 
- Maybe try to display the `self.num_events_this_day` in the interface and ask for a new screenshot?
- Try with different type of events to see if it is specific to Google or ics events somehow?

**Comment by anufrievroman** [comment]
Okay, I am almost sure why it is, let me guess, in your config  either or `display_holidays = No` or `birthdays_from_abook = No`? If so, then I know what the bug is...

**Comment by anufrievroman** [comment]
Okay, I think I fixed it in the current main branch. Could you please try deleting your AUR version and installing 3.0.1:
```
pipx install git+https://github.com/anufrievroman/calcure
```

**Comment by dvragulin** [comment]
I'm sorry for the long answer. Yes, it works! It looks just awesome!
We are waiting for an update in AUR :)

**Comment by anufrievroman** [comment]
Okay, thanks again for reporting and testing! About the AUR, I actually don't control the package, so I can only publish the release on PyPi and hope that the maintainer of AUR package will update it (but usually it takes some time).
